### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/erad2020#1]
As agreed recently, Jordi Figueras i Ventura (@jfigui from @meteoswiss-mdr) and Kai Mühlbauer (@kmuehlbauer) will be coordinating the course at ERAD 2020.

We met last week and decided to start right now by setting up the course repository and trying to establish kind of a timeline. Below there are some important dates where we need to fill in our timeline (in bold letters). Please fill in more points in the timeline at what dates we want to have special things fixed (eg. packages, tutors etc.)

## Timeline:
- ERAD Conference: August 31st to September 4th 2020
- **Short Course: August 30th 2020**
- **Repo/Course Finalizing: TBA**
- Late Registration: July 1st to August 25th 2020
- Travel Awards etc.: June 15th 2020
- Regular Registration: June 1st to June 30th 2020
- Notification for Acceptance: April 30th 2020
- Abstract Submission Deadline: March 25th 2020
- Early Bird Registration: March 1st to May 31st 2020
- **Course Description: March1st**
- Abstract Submission Opening: January 15th 2020

**Comment by meteoswiss-mdr** [comment]
Hi all,

Considering that the early bird registration starts March 1st I think that by that time we should have the course description ready.
